<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright The WildFly Authors
  ~ SPDX-License-Identifier: Apache-2.0
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.wildfly.tck</groupId>
        <artifactId>transactions-tck-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>transactions-tck-runner</artifactId>
    <name>WildFly Jakarta Transactions TCK Runner</name>

    <properties>
        <version.org.testng>7.9.0</version.org.testng>
        <wildfly.skip>false</wildfly.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>jakarta.transaction</groupId>
            <artifactId>jakarta.transaction-api</artifactId>
            <version>${version.jakarta.transaction.api}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.arquillian</groupId>
            <artifactId>wildfly-arquillian-container-managed</artifactId>
        </dependency>
        <dependency>
            <groupId>commons-lang</groupId>
            <artifactId>commons-lang</artifactId>
            <version>2.6</version>
        </dependency>

        <!-- Test dependencies -->
        <dependency>
            <groupId>jakarta.tck</groupId>
            <artifactId>transactions-tck</artifactId>
            <version>12.0.0-SNAPSHOT</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.tck.arquillian</groupId>
            <artifactId>tck-porting-lib</artifactId>
            <version>11.1.2</version>
        </dependency>
        <dependency>
            <groupId>jakarta.tck.arquillian</groupId>
            <artifactId>arquillian-protocol-javatest</artifactId>
            <version>11.1.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.tck.arquillian</groupId>
            <artifactId>arquillian-protocol-appclient</artifactId>
            <version>11.1.2</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.jboss.arquillian.junit5</groupId>
            <artifactId>arquillian-junit5-container</artifactId>
            <version>${version.org.jboss.arquillian}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.shrinkwrap.descriptors</groupId>
            <artifactId>shrinkwrap-descriptors-impl-javaee</artifactId>
            <version>${version.org.jboss.shrinkwrap.descriptors}</version>
        </dependency>
        <dependency>
            <groupId>org.jboss.arquillian.protocol</groupId>
            <artifactId>arquillian-protocol-servlet-jakarta</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-transactions-tck</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <includeGroupIds>jakarta.tck</includeGroupIds>
                            <includeArtifactIds>transactions-tck</includeArtifactIds>
                            <stripVersion>true</stripVersion>
                            <overWriteReleases>true</overWriteReleases>
                            <outputDirectory>${project.build.directory}/dependency/lib</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-antrun-plugin</artifactId>
                <executions>
                    <execution>
                        <id>configure-test-classpath</id>
                        <phase>process-test-classes</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <exportAntProperties>true</exportAntProperties>
                            <target>
                                <!-- Copy ts.jte file from platform-tck if it exists -->
                                <copy file="${basedir}/../../../../platform-tck/glassfish-runner/transactions-tck/transactions-tck-run/jakartaeetck/bin/ts.jte"
                                      tofile="${project.build.directory}/ts.jte"
                                      failonerror="true"/>
                                
                                <fileset id="jakarta-api-jars"
                                         dir="${jboss.home}${file.separator}modules/system/layers/base/jakarta/">
                                    <!-- Jakarta API's needed on the test class path -->
                                    <include name="**/transaction/api/main/*.jar"/>
                                </fileset>
                                <pathconvert pathsep=","
                                             property="jakarta.api.jars" refid="jakarta-api-jars"/>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>
                        ${addjdkexports}
                        ${addjdkopens}
                    </argLine>
                    <dependenciesToScan>
                        <dependency>jakarta.tck:transactions-tck</dependency>
                    </dependenciesToScan>
                    <systemPropertyVariables>
                        <arquillian.launch>tck-javatest</arquillian.launch>
                    </systemPropertyVariables>
                    <systemProperties>
                        <gc.args/>
                        <additional.vm.args>
                            ${failsafe.plugin.jdk17.args}
                        </additional.vm.args>
                    </systemProperties>
                </configuration>
                <executions>
                    <execution>
                        <id>default-test</id>
                        <configuration>
                            <skip>true</skip>
                        </configuration>
                    </execution>
                    <execution>
                        <id>transactions-tck</id>
                        <phase>test</phase>
                        <goals>
                            <goal>test</goal>
                        </goals>
                        <configuration>
                            <additionalClasspathElements>
                                <!--suppress MavenModelInspection -->
                                <additionalClasspathElement>${jakarta.api.jars}</additionalClasspathElement>
                            </additionalClasspathElements>
                            <classpathDependencyExcludes>
                                <exclude>jakarta.transaction:jakarta.transaction-api</exclude>
                            </classpathDependencyExcludes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>

</project>
